#!/usr/bin/env bash
#
# AcciAssist — all-in-one installer for a blank Ubuntu 24 VPS.
#
#   wget -qO install.sh https://raw.githubusercontent.com/ruolez/acciassist/main/install.sh
#   sudo bash install.sh
#
# Menu: Install (with optional Let's Encrypt SSL) · Update (from GitHub, runs
# DB migrations, prunes images) · Remove. Run as root.
#
set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────
REPO_URL="https://github.com/ruolez/acciassist.git"
APP_DIR="/opt/acciassist"
BRANCH="main"
COMPOSE_FILE="docker-compose.prod.yml"
POSTGRES_USER="acciassist"
POSTGRES_DB="acciassist"

# ── Output helpers ─────────────────────────────────────────────────────
c_reset=$'\033[0m'; c_blue=$'\033[1;34m'; c_green=$'\033[1;32m'
c_yellow=$'\033[1;33m'; c_red=$'\033[1;31m'
info()  { printf '%s==>%s %s\n' "$c_blue"   "$c_reset" "$*"; }
ok()    { printf '%s✓%s %s\n'   "$c_green"  "$c_reset" "$*"; }
warn()  { printf '%s!%s %s\n'   "$c_yellow" "$c_reset" "$*"; }
err()   { printf '%s✗%s %s\n'   "$c_red"    "$c_reset" "$*" >&2; }
die()   { err "$*"; exit 1; }

# ── Small utilities ────────────────────────────────────────────────────
need_root() { [ "$(id -u)" -eq 0 ] || die "Please run as root (sudo bash install.sh)."; }
has_cmd()   { command -v "$1" >/dev/null 2>&1; }
gen_secret(){ openssl rand -hex "${1:-32}"; }

detect_ubuntu() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    if [ "${ID:-}" = "ubuntu" ] && [[ "${VERSION_ID:-}" == 24.* ]]; then
      ok "Ubuntu ${VERSION_ID} detected."
      return
    fi
    warn "This installer targets Ubuntu 24. Detected: ${PRETTY_NAME:-unknown}."
  else
    warn "Could not detect the OS."
  fi
  read -rp "Continue anyway? [y/N] " a; [[ "$a" =~ ^[Yy] ]] || die "Aborted."
}

server_ip() {
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [ -n "$ip" ] || ip="$(curl -fsS https://api.ipify.org 2>/dev/null || true)"
  printf '%s' "${ip:-YOUR_SERVER_IP}"
}

# Read a single KEY=value from the installed .env
env_get() { grep -E "^$1=" "$APP_DIR/.env" 2>/dev/null | head -n1 | cut -d= -f2-; }

# docker compose wrapper, always run inside APP_DIR (so it finds .env)
compose() { ( cd "$APP_DIR" && docker compose -f "$COMPOSE_FILE" "$@" ); }

wait_for_db() {
  info "Waiting for the database to be ready…"
  local i
  for i in $(seq 1 30); do
    if compose exec -T db pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
      ok "Database is ready."; return 0
    fi
    sleep 2
  done
  die "Database did not become ready in time."
}

require_installed() {
  [ -d "$APP_DIR/.git" ] || die "AcciAssist is not installed at $APP_DIR. Run Install first."
}

# ── Dependency installation (assumes a blank server) ───────────────────
install_dependencies() {
  info "Installing system dependencies…"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y -qq
  apt-get install -y -qq ca-certificates curl git ufw openssl

  if ! has_cmd docker; then
    info "Installing Docker Engine…"
    curl -fsSL https://get.docker.com | sh
  fi
  systemctl enable --now docker >/dev/null 2>&1 || true
  docker compose version >/dev/null 2>&1 || die "Docker Compose plugin is missing."
  ok "Docker $(docker --version | awk '{print $3}' | tr -d ',') ready."

  info "Configuring firewall (22, 80, 443)…"
  ufw allow 22/tcp   >/dev/null 2>&1 || true
  ufw allow 80/tcp   >/dev/null 2>&1 || true
  ufw allow 443/tcp  >/dev/null 2>&1 || true
  yes | ufw enable   >/dev/null 2>&1 || true
  ok "Firewall configured."
}

# ── Prompt for and write the .env ──────────────────────────────────────
prompt_and_write_env() {
  local use_ssl domain admin_email admin_pass admin_pass2 site_address public_url cookie_secure
  echo
  read -rp "Enable HTTPS with Let's Encrypt (recommended for a domain)? [y/N] " use_ssl
  if [[ "$use_ssl" =~ ^[Yy] ]]; then
    while :; do
      read -rp "  Domain name (e.g. acciassist.com): " domain
      [ -n "$domain" ] && break
      warn "Domain cannot be empty."
    done
    site_address="$domain"
    public_url="https://$domain"
    cookie_secure="true"
    warn "Make sure DNS A record for '$domain' points to $(server_ip) before SSL can be issued."
  else
    site_address=":80"
    public_url="http://$(server_ip)"
    cookie_secure="false"
  fi

  echo
  read -rp "Admin email [admin@acciassist.com]: " admin_email
  admin_email="${admin_email:-admin@acciassist.com}"
  while :; do
    read -rsp "Admin password: " admin_pass; echo
    read -rsp "Confirm password: " admin_pass2; echo
    [ -n "$admin_pass" ] && [ "$admin_pass" = "$admin_pass2" ] && break
    warn "Passwords empty or do not match — try again."
  done

  local jwt_secret pg_pass
  jwt_secret="$(gen_secret 32)"
  pg_pass="$(gen_secret 24)"

  info "Writing $APP_DIR/.env …"
  umask 077
  cat > "$APP_DIR/.env" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — keep this file secret.
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$pg_pass
POSTGRES_DB=$POSTGRES_DB
DATABASE_URL=postgresql+asyncpg://$POSTGRES_USER:$pg_pass@db:5432/$POSTGRES_DB
JWT_SECRET=$jwt_secret
JWT_EXPIRE_MINUTES=720
CORS_ORIGINS=$public_url
ADMIN_EMAIL=$admin_email
ADMIN_PASSWORD=$admin_pass
COOKIE_SECURE=$cookie_secure
SITE_ADDRESS=$site_address
VITE_API_BASE=/api
EOF
  umask 022
  PUBLIC_URL="$public_url"
  ok "Configuration saved."
}

build_up_migrate() {
  info "Building images (first build can take a few minutes)…"
  compose build
  info "Starting services…"
  compose up -d
  wait_for_db
  info "Running database migrations…"
  compose run --rm backend alembic upgrade head
}

# ── Commands ───────────────────────────────────────────────────────────
cmd_install() {
  need_root; detect_ubuntu; install_dependencies
  if [ -d "$APP_DIR/.git" ]; then
    die "Already installed at $APP_DIR. Use the Update option instead."
  fi
  info "Cloning repository to $APP_DIR …"
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"

  prompt_and_write_env
  build_up_migrate

  info "Seeding initial data…"
  compose run --rm backend python -m app.seed

  echo
  ok "AcciAssist is installed and running."
  echo "   App:        $PUBLIC_URL"
  echo "   Admin:      $PUBLIC_URL/admin   (login: $(env_get ADMIN_EMAIL))"
  case "$(env_get SITE_ADDRESS)" in
    :80) : ;;
    *)   echo "   SSL:        Let's Encrypt cert is issued automatically once DNS resolves to this server." ;;
  esac
}

cmd_update() {
  need_root; require_installed
  info "Ensuring services are up before backup…"
  compose up -d db
  wait_for_db

  info "Backing up the database (keeps all settings/data)…"
  mkdir -p "$APP_DIR/backups"
  local ts; ts="$(date -u +%Y%m%dT%H%M%SZ)"
  compose exec -T db pg_dump -U "$(env_get POSTGRES_USER)" "$(env_get POSTGRES_DB)" \
    | gzip > "$APP_DIR/backups/db-$ts.sql.gz"
  ok "Backup written to backups/db-$ts.sql.gz"

  info "Pulling latest code from GitHub…"
  git -C "$APP_DIR" fetch --quiet origin "$BRANCH"
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"

  info "Rebuilding and restarting…"
  compose build
  compose up -d
  wait_for_db

  info "Applying database migrations…"
  compose run --rm backend alembic upgrade head

  info "Refreshing seed reference data (idempotent; never touches admin edits)…"
  compose run --rm backend python -m app.seed

  info "Cleaning unused Docker images…"
  docker image prune -f   >/dev/null 2>&1 || true
  docker builder prune -f >/dev/null 2>&1 || true

  ok "Update complete. Data and settings preserved."
}

cmd_remove() {
  need_root; require_installed
  warn "This stops AcciAssist and removes its containers, network, and built images."
  read -rp "Continue? [y/N] " a; [[ "$a" =~ ^[Yy] ]] || die "Aborted."

  compose down --remove-orphans --rmi local || true
  ok "Containers and images removed."

  echo
  warn "Deleting the data ALSO removes the database (all submissions, leads, admins) — irreversible."
  read -rp "Also delete the database, app files, and certificates? [y/N] " wipe
  if [[ "$wipe" =~ ^[Yy] ]]; then
    compose down -v || true
    rm -rf "$APP_DIR"
    ok "Everything removed. The server is clean and ready for a fresh install."
  else
    ok "Code/containers removed; database volume and $APP_DIR kept for a future reinstall."
  fi
}

# ── Menu ───────────────────────────────────────────────────────────────
banner() {
  printf '%s\n' "$c_blue"
  cat <<'EOF'
   _             _    _              _     _
  / \   ___ ___ (_)  / \   ___ ___ (_)___| |_
 / _ \ / __/ __|| | / _ \ / __/ __|| / __| __|
/ ___ \ (_| (__ | |/ ___ \\__ \__ \| \__ \ |_
/_/  \_\___\___||_/_/   \_\___/___/|_|___/\__|
EOF
  printf '%s  Ubuntu 24 installer\n\n' "$c_reset"
}

menu() {
  banner
  echo "  1) Install"
  echo "  2) Update   (pull latest, migrate DB, prune images)"
  echo "  3) Remove"
  echo "  4) Exit"
  echo
  read -rp "Choose an option [1-4]: " choice
  case "$choice" in
    1) cmd_install ;;
    2) cmd_update  ;;
    3) cmd_remove  ;;
    4) exit 0 ;;
    *) die "Invalid option." ;;
  esac
}

main() {
  case "${1:-}" in
    install) cmd_install ;;
    update)  cmd_update  ;;
    remove)  cmd_remove  ;;
    "")      menu ;;
    *)       die "Usage: $0 [install|update|remove]" ;;
  esac
}

main "$@"
